first_app/urls.py
from django.urls import path
from . import views

app_name = "first_app"
urlpatterns = [
    path("", views.first_page, name="first_page"),
    path("getplace/", views.index, name="index"),
    path("place/", views.places, name="second_page"),
    path("details/", views.more_details, name="detailed_information"),
    path("add/", views.add, name="add_place"),
]

where_to_go/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("first_app.urls"))]

first_app/models.py
from django.db import models

# Create your models here.

first_app/forms.py
from django import forms


class NewPlaceForm(forms.Form):
    name = forms.CharField(label="Назва місця", max_length=50, required=True)
    location = forms.CharField(label="Локація", max_length=50, required=False)
    description = forms.CharField(label="Опис", required=False)
    types = (
        ("1", "Поїсти"),
        ("2", "Розваги"),
        ("3", "Цікавий простір"),
        ("4", "Погуляти"),
    )
    type = forms.ChoiceField(label="Тип місця", choices=types, required=False)
    rating = forms.IntegerField(
        label="Рейтинг", required=True, min_value=1, max_value=5
    )

first_app/views.py
from datetime import date
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import numpy as np
from .destinations import get_place
from .forms import NewPlaceForm


def all_places_session(request):
    user_session = request.session.get("places", [])
    return user_session + get_place


def index(request):
    a = get_place
    weights = np.array([p["rating"] for p in a])
    weights = weights / weights.sum()
    selected_place = np.random.choice(a, p=weights)

    return render(request, "first_app/index.html", {"place": selected_place})


def places(request):
    return render(
        request, "first_app/allplaces.html", {"places": all_places_session(request)}
    )


def first_page(request):
    return render(request, "first_app/first_page.html")


def more_details(request):
    if request.method == "GET":
        name = request.GET.get("name")

        for place in all_places_session(request):
            if place["name"] == name:
                return render(request, "first_app/more_details.html", {"place": place})


def add(request):
    if request.method == "POST":
        form = NewPlaceForm(request.POST)
        if form.is_valid():
            # task = form.cleaned_data['task']
            place = {
                "name": form.cleaned_data["name"],
                "location": form.cleaned_data["location"],
                "description": form.cleaned_data["description"],
                "type": form.cleaned_data["type"],
                "rating": form.cleaned_data["rating"],
                "date_created": date.today().strftime("%Y-%m-%d"),
            }

            if "places" not in request.session:
                request.session["places"] = []
            request.session["places"].append(place)

            request.session.modified = True  # уточнити за зберігання

            return HttpResponseRedirect(reverse("first_app:second_page"))
        else:
            return render(request, "first_app/addplace.html", {"form": form})
    return render(request, "first_app/addplace.html", {"form": NewPlaceForm()})

first_app/templates/first_app/addplace.html
{% extends "first_app/base.html" %}
{% block content %}
    <form action="{% url 'first_app:add_place' %}" method="post" class="styled-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">тиць</button>
    </form>
{% endblock content %}

first_app/templates/first_app/allplaces.html
{% extends "first_app/base.html" %}
{% block content %}
    <ul>
        {% for place in places %}
            {% include "first_app/preview.html" with place=place full=False %}
        {% endfor %}
    </ul>
    <div class="add-btn-wrapper">
        <a href="{% url 'first_app:add_place' %}" class="btn">додай своє</a>
    </div>
{% endblock content %}

first_app/templates/first_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hmm where to go today</title>
    <link rel="stylesheet" href="{% static 'first_app/style.css' %}">
</head>
<body>
    <header>
        <nav>
            <li><a href="{% url 'first_app:first_page' %}">головна</a></li>
            <li><a href="{% url 'first_app:second_page' %}">усі місця</a></li>
            <li><a href="{% url 'first_app:add_place' %}">додати нове місце</a></li>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>16.09.2025 Глазкова Юлія</p>
    </footer>
</body>
</html>

first_app/templates/first_app/first_page.html
{% extends "first_app/base.html" %}
{% block content %}
<div class="first-page-wrapper">
    <h1>🎲Hmm.. Where to go today?🎲</h1>
    <p>Натисни на кнопочку аби дізнатися куди підемо сьогодні🧐</p>
    <form action="{% url 'first_app:index' %}" method="get">
        <button type="submit" class="btn">запропонуй мені місце</button>
    </form>
</div>
{% endblock content %}

first_app/templates/first_app/index.html
{% extends "first_app/base.html" %}
{% block content %}
    <h1>Сьогодні варто відвідати</h1>
    {% if place %}
        {% include "first_app/preview.html" with place=place %}
    {% else %}
        <p>Місць немає</p>
    {% endif %}
{% endblock content %}

first_app/templates/first_app/more_details.html
{% extends "first_app/base.html" %}
{% block content %}
    {% include "first_app/preview.html" with place=place full=True %}
{% endblock content %}

first_app/templates/first_app/preview.html
{% load static %}
<div class="place-card">
    <div class="place-img-wrapper">
        <img src="{% static 'first_app/monkey.jpeg' %}" alt="{{ place.name }}" class="place-img">
    </div>

    {% if full %}
        <h1 class="place-title">{{ place.name }}</h1>
    {% else %}
        <a href="{% url 'first_app:detailed_information' %}?name={{ place.name }}" class="place-title">
            {{ place.name }}
        </a>
    {% endif %}

    <p class="label">
        Опис:
        {% if place.description %}
            {% if full %}
                {{ place.description }}
            {% else %}
            {{ place.description|truncatewords:3 }}
            {% endif %}
        {% else %}
            Secret
        {% endif %}
    </p>

    <p class="label">
        Тип:
        {% if place.type %}
            {{ place.type }}
        {% else %}
            Secret
        {% endif %}
    </p>

    <p class="label">
        Локація:
        {% if place.location %}
            {{ place.location }}
        {% else %}
            Secret place👀
        {% endif %}
    </p>

    <p class="label">
        Рейтинг:
        {% if place.rating == 1 %}⭐
        {% elif place.rating == 2 %}⭐⭐
        {% elif place.rating == 3 %}⭐⭐⭐
        {% elif place.rating == 4 %}⭐⭐⭐⭐
        {% elif place.rating == 5 %}⭐⭐⭐⭐⭐
        {% endif %}

    </p>

    <p class="label">
        Дата відгуку: {{ place.date_created }}
    </p>
</div>